### ISSUE TITLE
Some mods patched only after closing error window (Mod Duplicates)

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/Bansoukou#4]
### Reproduce

Steps i get into issue:

1. I updated some mods
2. Removed all `-patched.jar` files and renamed `.disabled` back to `.jar`
  > This how my folder files looks like
  > ![explorer_UJpy6f7dpg](https://user-images.githubusercontent.com/936618/228480910-e950bf84-47f9-4fdc-9a69-bc303545c9f1.png)
3. Next, i launched game and get this error:
  > ![javaw_acEh9ctosn](https://user-images.githubusercontent.com/936618/228481071-4d13ee8e-8336-49af-ba3d-0aeca547859c.png)
4. This how `mods/` folder looks like when i see error above
  > ![explorer_XZTZGfBLAk](https://user-images.githubusercontent.com/936618/228481261-96690876-e492-4beb-ab8a-434856e5d69a.png)
5. As soon as i close MC window with error above, files renamed
  > ![image](https://user-images.githubusercontent.com/936618/228481668-707eacca-de90-45f0-a687-04506923ec1a.png)
6. I launch game again and everything working fine

Even though I have about 20 mods modified through Bansoukou, only these two mods create the error: `ImmersiveEngineering` and `BetterAnimalsPlus`.

### Logs
Logs that generated after step `5.`: [debug.zip](https://github.com/LoliKingdom/Bansoukou/files/11098494/debug.zip)

### Versions
- `mixinbooter-7.1` (happens with `7.0` too)
- `_bansoukou-4.3.1`

**Comment by Rongmario** [comment]
I'll take a look at both of those mods and see what's up, thanks.

**Comment by Krutoy242** [comment]
Issue is still actual! More and more players hit this issue running E2EE

![image](https://github.com/LoliKingdom/Bansoukou/assets/936618/d0dacc3c-d7fe-4ca5-8c5a-9409dbaabbec)

**Comment by Rongmario** [comment]
Got it, I'll probably have to rewrite -.-

**Comment by Krutoy242** [comment]
Video demonstration of files renamed only after i'm closing MC window.

https://github.com/LoliKingdom/Bansoukou/assets/936618/4d5c0edb-1693-4c6e-8641-b9397f6014a4

**Comment by Epikest** [comment]
can confirm this issue still happens, happened to my buddy and i today while running E2EE. for me it got fixed while creating a new instance.

**Comment by Rongmario** [comment]
I'm currently developing version 5 which will address all of these issues. Please stay put thank you!

**Comment by VladimirPlatun** [comment]
Hi! I am facing the same problem, can I count on fixing this error?

**Comment by Rongmario** [comment]
Fixed in v5.
