### ISSUE TITLE
Banoukou cant rename file `twilighttweaks-1.12.2-v1.0.2.jar.jar`

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/Bansoukou#5]
For some reason, [TwilightTweaks](https://www.curseforge.com/minecraft/mc-mods/twilight-tweaks) mod have jar file name `twilighttweaks-1.12.2-v1.0.2.jar.jar` with two `.jar.jar` at the end.

When i'm patching this mod with Bansoukou, it leaves both files:

![image](https://github.com/LoliKingdom/Bansoukou/assets/936618/40099a9c-347e-44b7-9eef-48336fb881f2)

[debug-1.log.gz](https://github.com/LoliKingdom/Bansoukou/files/13280478/debug-1.log.gz)

I dont know why, but leaving two same mods not crashing game, but instead, mod just not working. Renaming unpatched file to `twilighttweaks-1.12.2-v1.0.2.jar.disabled` fix the issue

**Comment by Krutoy242** [comment]
Issue is still actual, still waiting for the fix 👀

**Comment by KorewaLidesu** [comment]
> Issue is still actual, still waiting for the fix 👀

Because the build contains https://github.com/LoliKingdom/Bansoukou/commit/2b4f2bc26ca12415b5cfad93fd8e44123e87613b isn't publish yet

**Comment by Rongmario** [comment]
Fixed in v5.

**Comment by Omgise** [comment]
@Rongmario It seems the 1.7.10 branch of Bansoukou also has the exact same issue. Would it be possible for you to fix/backport the fix to 1.7.10 when you have time? Thanks!
